function name = getModelStringID(prefix, sampling_params)
name = sprintf('%s_ve%.2f_vx%.2f_pm%.2f_pD%.2f_gam%.2f_ns%d_b%d', ...
    prefix, sampling_params.var_e, sampling_params.var_x, ...
    sampling_params.p_match, sampling_params.prior_D, ...
    sampling_params.gamma, sampling_params.samples, sampling_params.batch);
end