function name = getModelStringID(params, ideal_observer)
if nargin < 2, ideal_observer = false; end
if ~ideal_observer
    name = sprintf('%dx%d_cinfo%.3f_sinfo%.3f_ve%.2f_vx%.2f_pm%.2f_pC%.2f_gam%.2f_ns%d_b%d', ...
        params.trials, params.frames, params.category_info, ...
        params.sensory_info, params.var_e, params.var_x, params.p_match, ...
        params.prior_C, params.gamma, params.samples, params.batch);
else
    name = sprintf('%dx%d_cinfo%.3f_sinfo%.3f_ve%.2f_pm%.2f_pC%.2f', ...
        params.trials, params.frames, params.category_info, ...
        params.sensory_info, params.var_e, params.p_match, params.prior_C);
end
end